spring:
  profiles: default
server:
  port: 8080
db:
  name: demodb
  url: "http://localhost:5984"

---
spring:
  profiles: development

server:
  port: 8080
db:
  name: hexacoredb
  url: "http://db:5984"
